# Generated by Django 4.1.7 on 2023-10-13 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmyevents', '0002_booking_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paidBy', models.CharField(max_length=50)),
                ('paidEvent', models.CharField(max_length=50)),
                ('paidDate', models.DateField()),
                ('paidtickets', models.IntegerField()),
                ('paidprice', models.IntegerField()),
                ('paidStatus', models.CharField(max_length=50)),
            ],
        ),
    ]
