# Generated by Django 4.1.7 on 2023-10-29 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmyevents', '0004_user_email_user_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phoneNumber',
            field=models.CharField(default='', max_length=10),
        ),
    ]
